export const paidUserGrowthTrend = [
  { date: "05-01", newPaid: 260, activePaid: 12600, monthly: 10480, yearly: 2120, churn: 82, netGrowth: 178 },
  { date: "05-05", newPaid: 330, activePaid: 13140, monthly: 10940, yearly: 2200, churn: 74, netGrowth: 256 },
  { date: "05-10", newPaid: 390, activePaid: 13940, monthly: 11620, yearly: 2320, churn: 91, netGrowth: 299 },
  { date: "05-15", newPaid: 470, activePaid: 14580, monthly: 12120, yearly: 2460, churn: 126, netGrowth: 344 },
  { date: "05-20", newPaid: 540, activePaid: 15120, monthly: 12580, yearly: 2540, churn: 118, netGrowth: 422 },
  { date: "05-25", newPaid: 610, activePaid: 15880, monthly: 13120, yearly: 2760, churn: 104, netGrowth: 506 },
  { date: "05-30", newPaid: 690, activePaid: 16420, monthly: 13480, yearly: 2940, churn: 132, netGrowth: 558 },
]

export const paidConversionTimeline = [
  { day: "D0", distribution: 18, cumulative: 18 },
  { day: "D1", distribution: 24, cumulative: 42 },
  { day: "D2", distribution: 14, cumulative: 56 },
  { day: "D3", distribution: 10, cumulative: 66 },
  { day: "D7", distribution: 16, cumulative: 82 },
  { day: "D14", distribution: 9, cumulative: 91 },
  { day: "D30", distribution: 9, cumulative: 100 },
]

export const paidAcquisitionSources = [
  {
    source: "YouTube",
    utmCampaign: "ai-shorts-demo",
    group: "Organic",
    paidUsers: 10280,
    paidConversion: "4.91%",
    churnRate: "2.8%",
    retention: "61%",
    arpu: "$58",
  },
  {
    source: "Referral",
    utmCampaign: "creator-referral",
    group: "Referral",
    paidUsers: 8420,
    paidConversion: "5.02%",
    churnRate: "2.4%",
    retention: "58%",
    arpu: "$64",
  },
  {
    source: "Google Search",
    utmCampaign: "seo-ai-video",
    group: "Organic",
    paidUsers: 7210,
    paidConversion: "3.84%",
    churnRate: "3.2%",
    retention: "54%",
    arpu: "$49",
  },
  {
    source: "Direct",
    utmCampaign: "brand-direct",
    group: "Organic",
    paidUsers: 6420,
    paidConversion: "3.67%",
    churnRate: "3.0%",
    retention: "52%",
    arpu: "$52",
  },
  {
    source: "Paid Ads",
    utmCampaign: "thumbnail-launch",
    group: "Paid",
    paidUsers: 3180,
    paidConversion: "3.17%",
    churnRate: "5.8%",
    retention: "34%",
    arpu: "$38",
  },
  {
    source: "Instagram",
    utmCampaign: "creator-carousel",
    group: "Paid",
    paidUsers: 2840,
    paidConversion: "3.15%",
    churnRate: "5.1%",
    retention: "38%",
    arpu: "$41",
  },
]

export const paidRegionAnalysis = [
  { country: "South Korea", paidUsers: 18420, revenue: 1018000, arpu: "$55", retention: "62%", upgradeRate: "18%" },
  { country: "United States", paidUsers: 11280, revenue: 721400, arpu: "$64", retention: "58%", upgradeRate: "21%" },
  { country: "Japan", paidUsers: 7240, revenue: 361600, arpu: "$50", retention: "51%", upgradeRate: "14%" },
  { country: "Russia", paidUsers: 3180, revenue: 120840, arpu: "$38", retention: "39%", upgradeRate: "8%" },
  { country: "Brazil", paidUsers: 2920, revenue: 119720, arpu: "$41", retention: "42%", upgradeRate: "10%" },
]

export const planDistribution = [
  {
    service: "Yettey",
    plan: "Starter",
    activeSubscribers: 18400,
    monthly: 16220,
    yearly: 2180,
    upgradeRate: "9.2%",
    downgradeRate: "1.4%",
    churnRate: "4.8%",
    avgDuration: "3.2 mo",
  },
  {
    service: "Yettey",
    plan: "Growth",
    activeSubscribers: 16820,
    monthly: 13440,
    yearly: 3380,
    upgradeRate: "16.8%",
    downgradeRate: "2.1%",
    churnRate: "3.6%",
    avgDuration: "5.8 mo",
  },
  {
    service: "Yettey",
    plan: "Pro",
    activeSubscribers: 9140,
    monthly: 6820,
    yearly: 2320,
    upgradeRate: "7.4%",
    downgradeRate: "1.8%",
    churnRate: "2.9%",
    avgDuration: "7.1 mo",
  },
  {
    service: "VPICK",
    plan: "Basic",
    activeSubscribers: 4860,
    monthly: 4380,
    yearly: 480,
    upgradeRate: "13.6%",
    downgradeRate: "1.2%",
    churnRate: "5.4%",
    avgDuration: "2.9 mo",
  },
  {
    service: "VPICK",
    plan: "Professional",
    activeSubscribers: 3260,
    monthly: 2380,
    yearly: 880,
    upgradeRate: "5.8%",
    downgradeRate: "1.6%",
    churnRate: "3.1%",
    avgDuration: "6.3 mo",
  },
]

export const upgradeDowngradeFlows = [
  {
    flow: "Starter -> Growth",
    users: 3280,
    avgTiming: "9.4 days",
    trigger: "Exported 10+ assets",
    revenueImpact: "$184K",
    direction: "Upgrade",
  },
  {
    flow: "Growth -> Pro",
    users: 1420,
    avgTiming: "18.2 days",
    trigger: "Reached 75% credit usage",
    revenueImpact: "$132K",
    direction: "Upgrade",
  },
  {
    flow: "Basic -> Professional",
    users: 980,
    avgTiming: "6.8 days",
    trigger: "First AI generation completed",
    revenueImpact: "$74K",
    direction: "Upgrade",
  },
  {
    flow: "Pro -> Growth",
    users: 420,
    avgTiming: "41.0 days",
    trigger: "Low workspace usage",
    revenueImpact: "-$19K",
    direction: "Downgrade",
  },
  {
    flow: "Growth -> Starter",
    users: 610,
    avgTiming: "35.6 days",
    trigger: "Team seats inactive",
    revenueImpact: "-$24K",
    direction: "Downgrade",
  },
]

export const subscriptionLifecycle = [
  { age: "1 month", subscribers: 12480, renewalRate: "72%", churnTiming: "Trial value not reached", lifetimeValue: "$42" },
  { age: "2 months", subscribers: 10420, renewalRate: "81%", churnTiming: "First renewal friction", lifetimeValue: "$88" },
  { age: "3 months", subscribers: 8420, renewalRate: "86%", churnTiming: "Credit limit pressure", lifetimeValue: "$141" },
  { age: "6 months", subscribers: 6120, renewalRate: "91%", churnTiming: "Team adoption stable", lifetimeValue: "$312" },
  { age: "12+ months", subscribers: 3180, renewalRate: "94%", churnTiming: "Expansion candidate", lifetimeValue: "$728" },
]

export const paidBehaviorIntelligence = [
  { behavior: "AI generation usage", users: 38420, frequency: "18.4 / mo", creditConsumption: "2.84M", upgradeCorrelation: "High" },
  { behavior: "Export frequency", users: 29180, frequency: "12.8 / mo", creditConsumption: "1.12M", upgradeCorrelation: "Very High" },
  { behavior: "Storage usage", users: 18420, frequency: "42.1 GB avg", creditConsumption: "N/A", upgradeCorrelation: "Medium" },
  { behavior: "Feature adoption", users: 24680, frequency: "4.2 features", creditConsumption: "820K", upgradeCorrelation: "High" },
  { behavior: "Team/workspace usage", users: 11280, frequency: "3.1 seats", creditConsumption: "640K", upgradeCorrelation: "Medium" },
]
